Create installation directory before running the bootstrapper
Otherwise it fails to install the client on a clean prefix:

$ mv ~/.var/app/com.discordapp.Discord{,.bak}
$ flatpak run com.discordapp.Discord
Missing sysmlink created by Discord after installation, running update_bootstrapper first...
Error: Other(unable to open database file: /home/user/.var/app/com.discordapp.Discord/config/discord/installer.db
Caused by:
    Error code 14: Unable to open the database file)